export const DeviceConfigurationValidationErrors= {
    "null value for AssetId": "Asset ID is missing in file data",
    "null value for AssetName": "Asset Name is missing in file data",
    "null value for Asset Parent Id": "Asset Parent ID is missing in file data",
    "null value for Group": "Group Name value is missing in file data",
    "null value for vendor": "Vendor Name value is missing in file data",
    "null value for Device Type": "Asset Type Name value is missing in file data",
    "null value for Latitude": "Latitude value is missing in file data",
    "null value for Longitude": "Longitude value is missing in file data",
    "Same value found for AssetId and ParentId": "File contains records where Asset ID is same as Parent Asset ID",
    "Change Timezone... This Timezone not found:": "Invalid value for Timezone found in file data",
    "Null value": "No data found in File",
    "Duplicate values for Device ID:": "Duplicate values for Asset ID",
    "Duplicate values for Device Name:": "Two or more records contain same Asset Name",
    "Saving List Is Empty": "File is Empty",
    "Invalid File": "Invalid File. One or more fields may be missing",
    "Exception in file":"File contains invalid data",
    "Asset Name is already present into database": "Two or more records contain same Asset Name",
    "Asset ID already exists":"Asset ID already exists",
    "Invalid Parent ID.": "One or more records contain invalid Parent Asset Id",
    "Invalid value for Asset class.": "null value for Asset class",
    "Invalid asset class value.": "Invalid asset class value.",
    "invalid value for Latitude": "Invalid value for Latitude.",
    "invalid value for Longitude": "Invalid value for Longitude.",
    "invalid value for IP": "Invalid value for IP Address."
}